Update generate-p12 - Require a valid integer input for "years until expiration" - Refactor output functions for consistency and clarity - Print messages in teal by default - Update _file_exists() to check for multiple files in one invocation - Unset inner functions via `trap`

diff --git a/generate-p12 b/generate-p12
--- a/generate-p12
+++ b/generate-p12
@@ -14,6 +14,9 @@ _generate_p12() {
     # However, any BM hostname or as little as "customer.realm" or "customer-realm" may be provided
 
     # Text formatting control characters for later use - by convention wrapped in {} when used below, for legibility
+    local red;     red="$(tput setaf 1)"
+    local teal;   teal="$(tput setaf 6)"
+    local default_color="$teal"
     local bold;   bold="$(tput bold)" # start bolding text
     local smul;   smul="$(tput smul)" # start underlining text
     local rmul;   rmul="$(tput rmul)" # stop underlining text
@@ -21,17 +24,51 @@ _generate_p12() {
     # Note: There is no `tput unbold`. `tput bold` is $'\E[1m', which you would generally undo with
     #  $'\E[0m' or $'\E[m', but those essentially match `tput sgr0`, clearing all formatting
 
-    _file_exists() {
-        if ! [ -f "$1" ]; then
-            echo "File not found: $1" >&2
-            return 1
+    # Unset inner functions before returning
+    trap 'unset -f _color _prompt _echo _bold _error _file_exists' RETURN
+    # Applies provided formatting (typically color) to output
+    _color() {
+        local color="$1" && shift
+        if [ -t 0 ]; then # input is not piped or redirected (_func hi)
+            printf "${color}%s\\n${reset}" "$@"
+        else # input is piped or redirected (cat file | _func, _func <file)
+            printf "${color}%s\\n${reset}" "$(cat)"
         fi
     }
-    _repeat() { # repeats a string n times
-        printf "%$2s" | sed "s/ /$1/g"
+    # Prints colored text without a trailing newline (for inline prompts)
+    _prompt() {
+        printf "${default_color}%s${reset}" "$*"
     }
+    # Prints colored text to stdout
+    _echo() {
+        _color "$default_color" "$@"
+    }
+    # Prints bold colored text to stdout
     _bold() {
-        echo "$bold$*$reset"
+        _color "$bold$default_color" "$@"
+    }
+    # Prints red text to stderr, with [ERR] preceding each line
+    _error() {
+        if [ -t 0 ]; then
+            local arg
+            for arg in "$@"; do
+                _color "$red" "[ERR] $arg" >&2
+            done
+        else
+            _color "$red" "[ERR] $(cat)" >&2
+        fi
+    }
+    # Checks if file(s) exist and prints an error message if not
+    _file_exists() {
+        local any_missing=0
+        local file
+        for file in "$@"; do
+            if [ ! -f "$file" ]; then
+                _error "File not found: $file"
+                any_missing=1
+            fi
+        done
+        return $any_missing
     }
 
     # TODO: We should just include the path in the filenames rather than changing to the directory and back
@@ -40,12 +77,12 @@ _generate_p12() {
     local old_dir="$PWD"
     # `cd` to working directory (or current if not provided, which will be a no-op)
     if ! cd "$wd"; then
-        echo "[ERR] Failed to change to specified directory" >&2
+        _error "Failed to change to specified directory"
         return 1
     fi
 
     local hostname
-    printf %s "Hostname (cert.staging.***): "
+    _prompt "Hostname (cert.staging.***): "
     read -r hostname
     echo #newline
     # Make sure we end up with a good hostname no matter what form it's provided in
@@ -68,14 +105,9 @@ _generate_p12() {
     local ca_key_filename="${hostname}_01.key"
     local ca_pass_filename="${hostname}_01.txt"
     local ca_serial_filename="${hostname}.srl" # CA serial is the only one which doesn't end in _01
-    local any_missing
-    # _file_exists prints filename if missing
-    _file_exists "$ca_cert_filename" || any_missing=true
-    _file_exists "$ca_key_filename" || any_missing=true
-    _file_exists "$ca_pass_filename" || any_missing=true
-    _file_exists "$ca_serial_filename" || any_missing=true
-    if [ "$any_missing" ]; then
-        echo "[ERR] Necessary file(s) missing, aborting p12 generation" >&2
+    # Verify necessary files exist, printing any which are missing
+    if ! _file_exists "$ca_cert_filename" "$ca_key_filename" "$ca_pass_filename" "$ca_serial_filename"; then
+        _error "${bold}Necessary file(s) missing, aborting p12 generation"
         return 1
     fi
 
@@ -87,7 +119,7 @@ _generate_p12() {
     local p12_filename="$user-$hostname.p12"
 
     # Print the filenames which will be used
-    cat <<EOF
+    _echo <<EOF
 ${smul}Using these filenames:${rmul}
   $ca_cert_filename
   $ca_key_filename
@@ -101,53 +133,63 @@ EOF
     echo #newline
 
     # Prompt for desired cert expiration, in years
-    local years
-    printf %s "Years until expiration: "
-    read -r years
+    while :; do # keep prompting until a nonzero integer is entered
+        _prompt "Years until expiration: "
+        read -r years
+        if [ "$years" -gt 0 ] 2>/dev/null; then
+            break
+        fi
+        echo "Please enter a valid integer." # terminal default color
+    done
     local days=$((years*365))
     echo #newline
 
     ### Step 1 of 3: Generate a CSR and private key
     # -nodes (no DES) means do not encrypt the generated private key
     if ! openssl req -new -sha256 -newkey rsa:2048 -nodes -out "$req_filename" -keyout "$key_filename"; then
-        _bold "[ERR] \`openssl req\` (step 1/3) failed - .req and .key files not generated" >&2
+        _error "${bold}\`openssl req\` (step 1/3) failed - .req and .key files not generated"
         return 1
     fi
-    printf '%s\n' '' "$(_bold "Created CSR:")" "$req_filename"
-    printf '%s\n' "$(_bold "Created private key:")" "$key_filename" ''
+    echo #newline
+    _bold "Created CSR:"
+    _echo "$req_filename"
+    _bold "Created private key:"
+    _echo "$key_filename"
+    echo #newline
 
     ### Step 2 of 3: Create a certificate from the CSR using the CA files and password
     # Read CA private key password from text file
     local pass
     if ! pass="$(cat "$ca_pass_filename")"; then
-        echo "[ERR] Failed to read CA password from $ca_pass_filename" >&2
+        _error "Failed to read CA password from $ca_pass_filename"
         return 1
     fi
     # Create X.509 certificate to be bundled with the user's private key in the PKCS#12 keystore
     if ! openssl x509 -req -in "$req_filename" -out "$pem_filename" -days "$days" -CA "$ca_cert_filename" -CAkey "$ca_key_filename" -passin "pass:$pass" -CAserial "$ca_serial_filename"; then
-        _bold "[ERR] \`openssl x509\` (step 2/3) failed - .pem file not generated" >&2
+        _error "${bold}\`openssl x509\` (step 2/3) failed - .pem file not generated"
         return 1
     fi
-    printf '%s\n' '' "$(_bold "Created X.509 intermediate certificate:")" "$pem_filename" ''
+    echo #newline
+    _bold "Created X.509 intermediate certificate:"
+    _echo "$pem_filename"
+    echo #newline
 
     ### Step 3 of 3: Bundle the private key (Step 1), the CA-signed certificate (Step 2), and CA certificate into a .p12 client certificate
     # Below lines are printed right before the "Enter Export Password" prompt from the pkcs12 export command
-    echo "${bold}NOTE:${reset} This encrypts the client certificate itself, so that it cannot be used without this password."
-    echo "${smul}secure prompt: no text will appear as you type${rmul}"
+    _echo "${bold}NOTE:${reset} ${default_color}This encrypts the client certificate itself, so that it cannot be used without this password."
+    _echo "${smul}secure prompt: no text will appear as you type${rmul}"
     if ! openssl pkcs12 -export -in "$pem_filename" -inkey "$key_filename" -certfile "$ca_cert_filename" -name "$user-$hostname" -out "$p12_filename"; then
-        _bold "[ERR] \`openssl pkcs12\` (step 3/3) failed - .p12 file not generated" >&2
+        _error "${bold}\`openssl pkcs12\` (step 3/3) failed - .p12 file not generated"
         return 1
     fi
-    printf '%s\n' '' "$(_bold "Created PKCS12 client certificate:")" "$p12_filename" ''
+    echo #newline
+    _bold "Created PKCS12 client certificate:" 
+    _echo "$p12_filename"
+    echo #newline
 
     ### DONE
     _bold "Finished successfully. Full path to p12:"
-    realpath "$p12_filename"
-
-    # Clean up internal functions to avoid polluting global namespace
-    unset -f _file_exists
-    unset -f _repeat
-    unset -f _bold
+    _echo "$PWD/$p12_filename"
 
     # Return to original directory
     if ! cd "$old_dir"; then
